// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLhPeO4UUkV13sSJ0ZJWvtBRmPvDjk1vA',
    appId: '1:577955661285:web:74c752936e009ab782db0c',
    messagingSenderId: '577955661285',
    projectId: 'portfolio-aadil-khan',
    authDomain: 'portfolio-aadil-khan.firebaseapp.com',
    storageBucket: 'portfolio-aadil-khan.appspot.com',
    measurementId: 'G-G4B4M37HGC',
  );
}
